#!/bin/bash

setxkbmap -layout gb
 xrandr --output DP-2 --primary --mode 2560x1440 --rotate normal --output DP-1 --mode 1920x1080 --rotate normal --left-of DP-2

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-1 -d 6 7 8 9 0

# Colors
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations -------------------------------#
bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true


# remove all rules first
bspc rule -r *:*


## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager compton

# Lauch notification daemon
dunst \
-geom "280x50-10+38" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch xsettingsd daemon
xsettingsd &

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
feh --bg-fill ~/.config/bspwm/wallpaper.png

# Start mpd
exec mpd &

# Start polybar
bash $HOME/.config/polybar/launch.sh

# Start picom
picom -f &

# Start bspwm scripts
bspcolors
/usr/bin/nm-applet &

